model_list:
  - model_name: flash
    litellm_params:
      model: "vertex_ai/gemini-1.5-flash-002"
      vertex_project: "boris001"
      vertex_location: "us-central1"

litellm_settings:
  callbacks: logger.logger